version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.1.1-alpine
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    ports:
      - 9000:9000
